version: "3.7"
services:
  app:
    build: .
    container_name: music_service
    restart: on-failure
    networks:
      local:
        ipv4_address: 192.168.1.2
    ports:
      - "9000:9000" 
  postgres:
    image: postgres:alpine3.17
    environment:
      POSTGRES_DB: "playlist"
      POSTGRES_USER: "gocloud"
      POSTGRES_PASSWORD: "gocloud"
      PGDATA: "/data/pgdata"
    volumes:
      - ./sql_scripts:/docker-entrypoint-initdb.d
      - ./data:/data
    networks:
      local:
        ipv4_address: 192.168.1.3
    ports:
      - "5432:5432"
networks:
  internal:
  local:
    ipam:
     driver: default
     config:
       - subnet: 192.168.1.0/24